products = [
    {
      '_id': '1',
      'name': 'Electric Guitar',
      'image': '/images/Guitar2.avif',
      'description':
        'Considered the standard by which other pickups are compared the Seymour Duncan JB with the throaty ’59 pickup are standard equipment in the KX-Custom.',
      'brand': 'Yamaha',
      'category': 'Electric Guitar',
      'price': 89.99,
      'countInStock': 10,
      'rating': 4.5,
      'numReviews': 12,
    },
    {
      '_id': '2',
      'name': 'Acoustic Guitar',
      'image': '/images/Guitar3.avif',
      'description':
        'Our Artist 12-String dreadnoughts harness all the energy our FST2 bracing delivers to create a wall of chorus shimmer that only 12-strings can make. ',
      'brand': 'Jackson',
      'category': 'Acoustic Guitar',
      'price': 599.99,
      'countInStock': 0,
      'rating': 4.0,
      'numReviews': 8,
    },
    {
      '_id': '3',
      'name': 'Classical Guitar',
      'image': '/images/Guitar1.avif',
      'description':
        'A wonderful tone, slightly brighter overall than a classical guitar and with a tremendous sound.In addition, the melody is very well defined and the basses as well, although being powerful, they are very balanced',
      'brand': 'Vintage',
      'category': 'Classical Guitar',
      'price': 929.99,
      'countInStock': 5,
      'rating': 3,
      'numReviews': 12,
    },
    {
      '_id': '4',
      'name': 'KRAMER Focus VT-211S',
      'image': '/images/Guitar4.avif',
      'description':
        'A Rock Classic Now in Ruby Red, Pewter Gray, Teal, and Purple.The Kramer Focus VT-211S is part of the Kramer Original Collection and is an ideal way to start your Kramer story! Featuring two powerful Kramer Alnico 5 SC-1 single coil pickups, a Kramer Alnico 5 humbucker, a 5-way pickup selector switch, and a Kramer Traditional tremolo',
      'brand': 'Kramer',
      'category': 'Electric Guitar',
      'price': 399.99,
      'countInStock': 11,
      'rating': 5,
      'numReviews': 12,
    },
    {
      '_id': '5',
      'name': 'Bugera Amplifier',
      'image': '/images/amplifier2.avif',
      'description':
        'The Tweaker-40’s 11 onboard Tweaker switches provide a wide range of vintage tones, from ultra-pristine cleans to oversaturated leads. ',
      'brand': 'Bugera',
      'category': 'Amplifier',
      'price': 49.99,
      'countInStock': 7,
      'rating': 3.5,
      'numReviews': 10,
    },
    {
      '_id': '6',
      'name': 'Acoustic Amplifer',
      'image': '/images/amplifier1.jpg',
      'description':
        'The original Sherwood Acoustic Guitar Combo was launched and one of the very first guitar amplifiers to enter the market and for over 30 years used throughout the world by the most highly respected acoustic guitar players',
      'brand': 'Orange',
      'category': 'Amplifier',
      'price': 29.99,
      'countInStock': 0,
      'rating': 4,
      'numReviews': 12,
    },
  ]
